### ISSUE TITLE
TP ended

### ISSUE THREAD

**Issue by LoicDelorme** [PolytechLyon/4a-isi3-tp1-2016-2017-groupe-2-delorme-kasprzyk#1]
@Slashgear as suggested into your FB message :)

**Comment by Slashgear** [comment]
Voici mes retours, je ne ferais pas aussi détaillé pour tout les groupes (j'aurai pas forcément le temps, mais au final vu que ces retours sont publiques, j'espère que d'autres les liront):

* 👍 pour l'essai découpage en package

* 👍 pour l'implémentation de l'adapteur et l'iterator abstrait

* 💡 UndirectedGraph peut être responsable de la création du directed graph. Pas obligé de la passer en paramètre du constructeur.

* ⚠️  Normalement pas de fichier propre aux IDE dans le repository (il faut update sont gitignore)

* 💡 On peut parcourir une map de manière fonctionnelle (pour l'exemple du toString)
```java
exampleMap.entrySet().forEach(entry -> {
});
```

* 👍 Rapport super/trop détaillé. Mais c'est cool. Le markdown, votre retour , ça va ?

* 💡 Je ne suis pas un partisan de la javadoc. Je préfère faire plus attention à mon nommage. Je pense que le code doit d'abord se comprendre de lui seul.
Je sors pas ça de mon chapeau, je l'ai lu dans un super bouquin de référence [Clean Code](https://www.amazon.fr/Clean-Code-Handbook-Software-Craftsmanship/dp/0132350882)
Cette idée fait encore débat dans la communauté des devs.

```java
/**
 The graph.
*/
protected final IGraph graph;
```
Par exemple, ici on se doute que c'est pas une banane.

**Comment by LoicDelorme** [comment]
Merci pour vos retours. Nous avons corrigé les éléments soulignés par votre réponse.

Pour la javadoc, je comprend votre point de vue et c'est parfois lourd pour pas grand chose. Dans le cadre de ce TP, les attributs ont finalement peut de métier derrière ce qui n'est pas toujours la cas... A challenger selon le projet je pense.

Concernant MarkDown, très bon outil pour les rapports ! Avez-vous des conseils sur ce langage (faire des rapports un peu plus complexe, stylisé le rapport, etc...) ? Un IDE dédié avec un rendu réel ? Car les plugins des IDEs classiques produisent rapidement des rendus moches et loin de ce qu'on voit sur Github...

**Comment by Slashgear** [comment]
Pour le rapport, on peut difficilement faire autrement avec Markdown, ça se veut simple.

Les plugins IDE, c'est sur c'est pas génial, sinon tu peux l'éditer directement sur Github avec la preview en temps réel.

Si tu veux faire des rapports/de la doc, de manière hyper sympa t'as Asciidoc avec Asciidoctor (je te laisse chercher.

**Comment by LoicDelorme** [comment]
Dernier commit envoyé :)

On peut clore l'issue ?
